#!/bin/bash
set -f

# This should retrieve the location of the script in a reasonably reliable way.
[[ "$(type -ft realpath)" == "file" ]] && cwd="$(dirname "$(realpath -q "$0")")" || cwd="$(dirname $0)"
PATH="$cwd:$cwd/conf/bin:$PATH"

# Configuration variables.
sicbin="$cwd/conf/bin/sic"
chans="$cwd/conf/channels"
pipe="$cwd/conf/pipes/"
scriptdir="$cwd/conf/scripts"
script_list=(':')
PATH="$cwd:$cwd/conf/bin:$PATH"

exec 3>> $pipe/out

join_channels() {

	# This line is for my testing config.
	[[ -f "$cwd/.chans" ]] && chans="$cwd/.chans"

	# Read from channel file and join channels
	cat "$chans" |
	while read line; do
		[[ "${line:0:1}" == "#" ]] && echo ":j $line" > $pipe/in
	done
	
}

run_scripts() {
	[[ "$nick" == "$bot_nick" ]] && return
	for script in "${script_list[@]}" ; do
		"$script"
	done
}

join_channel() {
	echo ":j $1 $2" > $pipe/in
}

leave_channel() {
	echo ":j $1 $2" > $pipe/in
}

add_channel() {
	echo "$@" >> $chans
	echo ":j $1 $2" > $pipe/in
}

rm_channel() {
	# The only instance of awk. Not really integral 
	# to running the bot, so I'm going to let it slide.
	awk "/$1/ {next} {print}" $cwd/.ctemp
	mv $cwd/.ctemp $pipe/channels
}

# Load all the scripts when sourcing this file

quit_bot() {
	echo ":quit" > $pipe/in
}

# Send to outfile.
botlog() {
	echo "$@" >&3
}

botsay() {

	# Tokenize input
	read -ra toks <<< "${@//$'\n'/$' '}"

	chan="${toks[0]}"
	mesg="${toks[@]:1}"

	# Split at every 400th character, so the 
	# message isn't too long for the server.
	for ((c = 0; c < "${#mesg}"; c+= 400)); do
		echo ":m $chan ${mesg:c:c+400}" > $pipe/in
	done

}

scripts_reload() {
	set +f
	script_list=(':')
	for script in "$scriptdir"/*; do
		if [[ -x "$script" && -f "$script" ]]; then
			source "$script"
			botlog "loading script: $script"
		else
			botlog "not loading script: $script, needs to be marked executable"
		fi
	done
	set -f
}

load_script() {
	script_list+=("$1")
}


if [[ "$1" == "join" ]]; then
	join_channel $2 $3
elif [[ "$1" == "part" ]]; then
	leave_channel "$2"
elif [[ "$1" == "autojoin" ]]; then
	join_channels	
elif [[ "$1" == "add" ]]; then
	add_channel "$2" "$3"
elif [[ "$1" == "remove" ]]; then
	rm_channel "$2"
elif [[ "$1" == "say" ]]; then
	botsay "${@:2}"
elif [[ "$1" == "kill" ]]; then
	quit_bot "${@:1}"
else
	scripts_reload
fi
