#!/bin/bash
set -f

# Configuration locations
cwd=$(dirname "$0")

# Source some larger scripts
source "$cwd/conf/bot.conf"
[ -e "$cwd/.botconf" ] && source "$cwd/.botconf"
source ctrlbot
joinset="premotd"

botstart() {

	# Create input pipe
	if [ ! -p "$pipe/in" ] ; then
		mkfifo "$pipe/in"
		touch "$pipe/out"
	fi

	# Start the process, pipe output to main loop.
	sic -h "$network" -p "$port" -n "$bot_nick" <> $pipe/in |
	while read line; do

		set -- $line
		echo "$line" >> $pipe/out

		if [ "$joinset" = "premotd" ]; then # Don't awk more than necessary
			[ $(echo "$line" | awk '{print $5}') = "376" ] && joinset="postmotd"
		elif [ "$joinset" = "postmotd" ] ; then
			echo "Joining channels... " >> $pipe/out
			join_channels
			joinset="done"
			botsay "nickserv $bot_pass"
		elif [ "$joinset" = "done" ]; then
			channel="$1"
			nick="$(echo "$5" | sed -e 's/[\>\<]//g')"
			message="${@:6}"
			[ "$channel" == "$bot_nick" ] && channel="$nick"
			[ "$6" == '!reload' ] && bot_load
			run_scripts
		fi

	done

}

bot_load() {
	echo "Reloading ... " >> $pipe/out
	source ctrlbot
	echo "done." >> $pipe/out
}

# For internal use, or non daemon use.
if [ "$1" == "daemon" ] ; then
	botstart
else
	$0 "daemon"&
	exit 0
fi

