#!/bin/bash

#chan=$(echo "$@" | awk '{print $1}')
#date=$(echo "$@" | awk '{print $3}')
#time=$(echo "$@" | awk '{print $4}')
#nick=$(echo "$@" | awk '{print $5}')
#said=$(echo "$@" | awk '{print $6-

#echo -e "CHAN: $chan\nDATE: $date\nTIME: $time" > scripts/out
